# Generated by Django 2.1.5 on 2019-02-21 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='pending', max_length=255)),
                ('amount', models.FloatField(default=10.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
