# Generated by Django 2.1.5 on 2019-02-01 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.CharField(default='some description', max_length=255),
        ),
    ]
