# Generated by Django 2.1.5 on 2019-02-02 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_comment_topic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='sub_category',
            new_name='subcategory',
        ),
    ]
