# Generated by Django 2.1.5 on 2019-02-02 16:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_auto_20190202_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 2, 16, 55, 21, 182648)),
        ),
    ]
