# Generated by Django 2.1.5 on 2019-02-19 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0008_auto_20190219_1324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='created_by',
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='comment',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.Topic'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='topic',
            name='description',
            field=models.CharField(max_length=255),
        ),
    ]
